### PR TITLE
Upgrade sandbox-buildkite-plugin to v2 to fix builds on Julia 1.11

### PR DESCRIPTION
**Pull request by fredrikekre**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
I assume we will need to do this for all Buildkite docs?

**Comment by fredrikekre** [comment]
Maybe. Which are the other ones?

**Comment by ChrisRackauckas** [comment]
DiffEqFlux.jl, SciMLSensitivity.jl

**Comment by fredrikekre** [comment]
No they don't use Sandbox.jl.

**Pull request merged**
