### PR TITLE
add StructuralIdentifiability

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
It holds back ModelingToolkit to v8.11

https://github.com/SciML/SciMLDocs/runs/6982966773?check_suite_focus=true#step:4:239

which is pre-ArrayInterface v6 + ArrayInterfaceCore. Maybe one of the dependencies are holding it back. @iliailmer

**Comment by iliailmer** [comment]
Once https://github.com/SciML/StructuralIdentifiability.jl/pull/77 is resolved, the compatibility will work. I tried forcing the installation of MTK@8.14 and got an error from `GroebnerBasis` which will be removed from `StructuralIdentifiability` by https://github.com/SciML/StructuralIdentifiability.jl/pull/77

**Comment by ChrisRackauckas** [comment]
Got it thanks!

**Comment by iliailmer** [comment]
Hi @ChrisRackauckas this should be fixed now with StructuralIdentifiability.jl 0.4.0

**Comment by ChrisRackauckas** [comment]
🎉

**Pull request merged**
