### PR TITLE
Transition to MultiDocumenter

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
This will make the documentation a lot simpler to navigate and a lot simpler to maintain in the long run. Also, it'll fix the fact that the build times are essentially infinite as we start to mark more of the tutorials to build at docs build time, which is happening throughout the ecosystem. MultiDocumenter just takes the built docs, instead of rebuilding them all here (which already would take around 6-7 hours to do correctly). This also makes it versioned, so it can serve as the canonical website for all of the docs in the future. Badges will thus need to be updated to always point to this (even for the benchmarks and tutorials).

However, there are a few outstanding issues that need to be solved in order to really complete this switch:

- [x] We still have a few repos which are simply using their README as the documentation. MultiDocumenter.jl does not support this. The answer is simple: setup Documenter.jl on those repos. 
- [x] What do we do about the high level documentation? We have a lot of summaries of domains that we do not want to lose. Where do we put these summary pages? I guess SciMLDocs should build a documenter doc on the fly, and then incorporate them as the high level?
- [x] How do we do hierarchical setups in the module choices? For example, Equation Solvers is a whole domain with like 8 modules and a summary page. What we would want here is a drop down menu, which allows for an Equation Solvers summary page just listed as "Summary", and then each module by name "LinearSolve, NonlinearSolve, ...", and then the top bar of the SciMLDocs shows "Home, Equation Solvers, Uncertainty Quantification, ..." with clear indication of being dropdowns.

Tracking README packages:

- [x] "FEniCS" => "https://github.com/SciML/FEniCS.jl",
- [x]  "SciMLStyle" => "https://github.com/SciML/SciMLStyle",
- [x] "COLPRAC" => "https://github.com/SciML/ColPrac",
- [x] "RuntimeGeneratedFunctions" => "https://github.com/SciML/RuntimeGeneratedFunctions.jl",
- [x] "MuladdMacro" => "https://github.com/SciML/MuladdMacro.jl",
- [x] "SBMLToolkit" => "https://github.com/SciML/SBMLToolkit.jl",
- [x] "CellMLToolkit" => "https://github.com/SciML/CellMLToolkit.jl"

@paulflang can you setup documentation for SBMLToolkit and CellMLToolkit? @devmotion can you do MuladdMacro (probably just make it a page that matches the README, and a docstring?), and DataInterpoations? 

@pfitzseb some of these questions are to you.

### CODE REVIEW

**Comment by pfitzseb** [comment]
> What do we do about the high level documentation? 

Yeah, you can just set up a separate action here that builds high-level docs and pushes them to a separate branch.

> How do we do hierarchical setups in the module choices?

https://github.com/JuliaComputing/MultiDocumenter.jl/issues/14

**Comment by paulflang** [comment]
@ChrisRackauckas : looks like CellMLtk already has Documenter docs. Is there anything I shall look into?

**Comment by ChrisRackauckas** [comment]
Thanks Paul. Those look good. If you could tackle MuladdMacro.jl next that would be helpful.

**Comment by pfitzseb** [comment]
Version 0.2 of MultiDocumenter supports an additional level of navigation (see the [readme](https://github.com/JuliaComputing/MultiDocumenter.jl) for an example).

**Comment by ChrisRackauckas** [comment]
Okay, I think everything is handled? Let's see how this goes.

**Comment by ChrisRackauckas** [comment]
welp, here goes nothing

**Comment by pfitzseb** [comment]
This doesn't deploy docs anywhere, does it?

**Comment by ChrisRackauckas** [comment]
Yeah, just found that out 😅 .

**Pull request merged**
