### PR TITLE
add DiffEqJump

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by isaacsas** [comment]
Is the plan to ultimately break apart the DifferentialEquations docs and/or listing for them here?

**Comment by ChrisRackauckas** [comment]
The DifferentialEquations docs still have a place, but the external bits should become completed package docs. It should really focus on the DEProblem/DEAlgorithm documentation, and all of the stuff associated with that, which is already a huge set of docs. Splitting also lets each package run doctests to ensure the examples aren't failing, something hard with just the big DiffEq docs. So anything that's not in the main core is getting its own docs, and then everything pooling here to have that same searchability effect, but even better.

**Comment by ChrisRackauckas** [comment]
Needs a DiffEqJump release first.

**Comment by isaacsas** [comment]
I made a release but no stable branch got built for some reason.

**Pull request merged**
