### PR TITLE
try different solver optimization under uncertainty showcase

### PR DESCRIPTION
**Pull request by ArnoStrouwen**
LBFGS started returning NaN, don't know why.
Try different solver.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Failed

**Comment by ArnoStrouwen** [comment]
It got further than before, the first optimization problem now solves correctly.
The second, however, seems to time out.
Did something change in Optimization.jl that could cause this?

**Comment by ChrisRackauckas** [comment]
@Vaibhavdixit02

**Comment by ArnoStrouwen** [comment]
It's working locally for me now.
No need to look further into this.
The constrained control problem was weirdly formulated with discontinuities.
I made it more robust.

If CI passes, can be merged in.

**Pull request merged**
